#  2.155/2.156 Python Intro Office Hours
This notebook serves as a reference for basic python usage and setup. We hope that going over the basics in this notebook will enable you to explore python programming and introduce the basics to you so you can start coding on your own!

## Introduction to Python Environment Setup
First you have to setup your python development environment
In this section, we'll cover how to set up your Python development environment using Miniforge, which is a smaller and more flexible version of Anaconda. Miniforge provides a way to create isolated environments where you can manage different versions of Python and its libraries without interfering with system-wide installations.

We'll cover installation for the following platforms:
- **Windows**
- **Linux**
- **Mac**
- **Google Colab**



### Miniforge Installation

#### Windows

1. **Download Miniforge for Windows**  
   Go to the [Miniforge GitHub page](https://github.com/conda-forge/miniforge) and download the installer for Windows. Choose the appropriate version based on your system (32-bit or 64-bit).

2. **Run the installer**  
   - Follow the installer prompts and ensure that you select the option to add Miniforge to your system's PATH.

3. **Verify Installation**  
   Open Command Prompt and run:
   ```bash
   mamba --version
   ```
   You should see the installed version of `conda/mamba`.

4. **Create a new Python environment**  
   You can now create an isolated Python environment with:
   ```bash
   mamba create -n myenv python=3.10
   ```
   Activate the environment:
   ```bash
   mamba activate myenv
   ```

#### Linux/Mac
1. **Download and Run the installer**  
   In your terminal run the following:
   ```bash
   curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
   ```
   Then install by running:

   ```bash
   bash Miniforge3-$(uname)-$(uname -m).sh
   ```
   Follow the prompts and ensure to add Miniforge to your system's PATH.

   ****Optional****: Remove downloaded file by running:

   ```bash
   rm Miniforge3-$(uname)-$(uname -m).sh
   ```
   
3. **Verify Installation**  
   Open terminal and run:
   ```bash
   mamba --version
   ```
   You should see the installed version of `conda/mamba`.

4. **Create a new Python environment**  
   You can now create an isolated Python environment with:
   ```bash
   mamba create -n myenv python=3.10
   ```
   Activate the environment:
   ```bash
   mamba activate myenv
   ```

### Why Use Conda/Mamba?

Conda and Mamba are popular package managers for Python and other languages. They offer several advantages:

- **Environment Management**: Conda/Mamba allows you to create isolated environments, making it easy to manage multiple projects with different dependencies.
- **Cross-Platform Compatibility**: Both work across Windows, macOS, and Linux, ensuring a consistent experience across different systems.
- **Efficient Dependency Resolution**: Mamba is faster than Conda in resolving dependencies, making package installation much quicker.
- **Precompiled Packages**: They offer precompiled binaries, reducing the complexity of setting up and managing libraries with C/C++ extensions.
- **Portability**: You can easily move your environment across different machines and compute infrastructure by exporting the environment to a `.yml` file. This file lists all the required packages, enabling reproducibility and seamless migration.


Now let's download an example yml file with the packages we will be needing and install them using mamba:

In [ ]:
# lets import somthing that does not exist in colab (This will throw an error)
from sksparse.cholmod import cholesky

ModuleNotFoundError: No module named 'sksparse'

In [ ]:
# First clone our demo repository
!git clone https://github.com/ahnobari/2.155-Python-Demo.git

fatal: destination path '2.155-Python-Demo' already exists and is not an empty directory.


UsageError: Line magic function `%%` not found.


In [ ]:
# install the needed packages (we will ask the notebook to not pring the installation logs)
%%capture
!mamba env update -n base -f 2.155-Python-Demo/env.yml

In [ ]:
# now this should work
from sksparse.cholmod import cholesky

# Introductory Python
Below are the very basics of python including loops and logical statements and so on. We expect you to already know about these concepts and figure out how to them on your own.

## Python Basics

### 1. Basic Python Syntax and Printing

Python is an interpreted language, which means it processes code line by line, allowing you to interact with the language directly. In this section, we will introduce basic syntax, expressions, and how to print output to the console.

---

#### Syntax
- **Code**: The sequence of instructions that the computer follows.
- **Syntax**: A set of rules that define how Python code must be written.
- **Output**: Messages printed to the user by a program.
- **Console**: The area where output is displayed. Here we don't deal with this as everything is printed in the notebook.

In [ ]:
# Let's start by printing a simple statement in Python
print("Hello, Python!")  # This will output: Hello, Python!

Hello, Python!


### 2. Expressions and Arithmetic Operations

An **expression** is a combination of values and operators that the interpreter evaluates to produce a result.

---

#### Example: Simple Arithmetic Expressions
We can use arithmetic operations like addition, subtraction, multiplication, and division. Let’s try a simple one:

In [ ]:
# Simple arithmetic operations
result = 1 + 2 * 3  # According to precedence, multiplication is done first
print("Result of 1 + 2 * 3:", result)  # Output: 7

Result of 1 + 2 * 3: 7


### 3. Arithmetic Operations and Precedence

Python follows a specific order of operations when evaluating expressions. This order is called **operator precedence**.

- **Precedence**: Operators with higher precedence are evaluated first.
- **Parentheses** can be used to force a certain order of evaluation.

---

#### Arithmetic Operators:
- `+`: Addition
- `-`: Subtraction
- `*`: Multiplication
- `/`: Division
- `%`: Modulus (Remainder)
- `**`: Exponentiation

#### Example: Operator Precedence

In [ ]:
# Precedence Example
result = (1 + 3) * 4  # Parentheses change the default precedence
print("Result of (1 + 3) * 4:", result)  # Output: 16

Result of (1 + 3) * 4: 16


In [ ]:
# Without parentheses
result = 1 + 3 * 4  # Multiplication is done first
print("Result of 1 + 3 * 4:", result)  # Output: 13

Result of 1 + 3 * 4: 13


### 4. Integer and Real Number Operations

Python can handle both integer and real number (floating-point) operations.

---

#### Example: Integer Division
When dividing two integers using `/`, Python will return a floating-point result.

In [ ]:
# Integer Division
result = 15 // 2  # Integer division using //
print("Integer division of 15 // 2:", result)  # Output: 7

Integer division of 15 // 2: 7


#### Example: Real Number Division

In [ ]:
# Real number division
result = 15 / 2  # Regular division
print("Real division of 15 / 2:", result)  # Output: 7.5


Real division of 15 / 2: 7.5


---

#### Mixing Integers and Reals:
When integers and real numbers are mixed, Python converts the result into a real number.

In [ ]:
# Mixing integers and reals
result = 7 / 3 * 1.2 + 3 / 2
print("Mixed division and multiplication result:", result)  # Output: 4.3

Mixed division and multiplication result: 4.300000000000001


### 5. Printing with Formatted Strings

In addition to printing multiple items with commas, you can also use **formatted strings** to make your output cleaner.

---

#### Example: Using `f-strings` (formatted strings)

In [ ]:
# Formatted strings (f-strings)
name = "John"
age = 30
print(f"My name is {name} and I am {age} years old.")  # Output: My name is John and I am 30 years old.

My name is John and I am 30 years old.


You can control the width, precision, and alignment of the output using formatted strings.

#### Example: Controlling Decimal Precision

In [ ]:
# Controlling decimal precision
pi = 3.141592653589793
print(f"Pi rounded to 2 decimal places: {pi:.2f}")  # Output: Pi rounded to 2 decimal places: 3.14

Pi rounded to 2 decimal places: 3.14


#### Example: Aligning Text
You can align text using `<`, `>`, and `^` for left, right, and center alignment, respectively.

In [ ]:
# Aligning text
print(f"{'left aligned':<15} | {'right aligned':>15}")  # Output: left aligned    |   right aligned

left aligned    |   right aligned


## Python Math Commands

Python provides a variety of built-in mathematical functions and constants through the `math` module. To access these functions, you need to import the `math` module.

---

### Common Math Functions:

- `abs(value)`: Returns the absolute value of the number.
- `ceil(value)`: Rounds a number up to the nearest integer.
- `floor(value)`: Rounds a number down to the nearest integer.
- `sqrt(value)`: Returns the square root of a number.
- `log(value)`: Returns the natural logarithm (base `e`).
- `log10(value)`: Returns the logarithm of the value to base 10.
- `sin(value)`: Returns the sine of an angle in radians.
- `cos(value)`: Returns the cosine of an angle in radians.
- `tan(value)`: Returns the tangent of an angle in radians.
- `max(value1, value2)`: Returns the maximum of two values.
- `min(value1, value2)`: Returns the minimum of two values.
- `round(value, digits)`: Rounds the number to the specified number of digits.
- `pi`: A constant for the value of pi (`π ≈ 3.14159`).
- `e`: A constant for the base of the natural logarithm (`e ≈ 2.71828`).

---

Below is a demonstration of some key math functions:

In [ ]:
# Importing the math module
import math

# Demonstrating key math functions
print("Absolute value of -8:", abs(-8))                  # Output: 8
print("Ceiling of 4.2:", math.ceil(4.2))                 # Output: 5
print("Floor of 4.8:", math.floor(4.8))                  # Output: 4
print("Square root of 25:", math.sqrt(25))               # Output: 5.0
print("Natural logarithm of 5:", math.log(5))            # Output: 1.609437...
print("Base-10 logarithm of 1000:", math.log10(1000))    # Output: 3.0
print("Sine of pi/2 radians:", math.sin(math.pi / 2))    # Output: 1.0
print("Value of pi:", math.pi)                           # Output: 3.141592653589793

Absolute value of -8: 8
Ceiling of 4.2: 5
Floor of 4.8: 4
Square root of 25: 5.0
Natural logarithm of 5: 1.6094379124341003
Base-10 logarithm of 1000: 3.0
Sine of pi/2 radians: 1.0
Value of pi: 3.141592653589793


---

You can explore more functions from the `math` module by visiting the official [Python math module documentation](https://docs.python.org/3/library/math.html).

In the next section, we will dive deeper into Python functions and variables.

## Logical Statements and If/Else

### Logical Operators

Logical expressions in Python use **relational operators** to compare values. These operators return either `True` or `False` based on the condition.

#### Relational Operators:
- `==`: Equals
- `!=`: Not equal to
- `<`: Less than
- `>`: Greater than
- `<=`: Less than or equal to
- `>=`: Greater than or equal to


In [ ]:
# Example: Relational operators
x = 10
y = 20

print("Is x equal to y?", x == y)  # Output: False
print("Is x not equal to y?", x != y)  # Output: True
print("Is x greater than y?", x > y)  # Output: False
print("Is x less than or equal to y?", x <= y)  # Output: True

Is x equal to y? False
Is x not equal to y? True
Is x greater than y? False
Is x less than or equal to y? True


### Logical Expressions

Logical expressions can also be combined using **logical operators**:
- `and`: Returns `True` if both conditions are true.
- `or`: Returns `True` if at least one condition is true.
- `not`: Negates the result of a logical expression.

#### Example:

In [ ]:
# Example: Logical expressions
a = 5
b = 15

print("Is a < 10 and b > 10?", a < 10 and b > 10)  # Output: True
print("Is a > 10 or b > 10?", a > 10 or b > 10)  # Output: True
print("Not a > b:", not a > b)  # Output: True

Is a < 10 and b > 10? True
Is a > 10 or b > 10? True
Not a > b: True


### If Statements

An **if statement** allows your program to execute certain code only if a specific condition is `True`.

#### Syntax:
```python
if condition:
    # code to execute if condition is true
```

In [ ]:
gpa = 3.5
if gpa > 3.0:
    print("You qualify for the scholarship!")  # This will print

You qualify for the scholarship!


### If/Else Statements

An **if/else statement** allows your program to choose between two sets of instructions based on whether a condition is `True` or `False`.

#### Syntax:
```python
if condition:
    # code to execute if condition is true
else:
    # code to execute if condition is false
```

In [ ]:
gpa = 2.5
if gpa > 3.0:
    print("You qualify for the scholarship!")
else:
    print("You do not qualify for the scholarship.")

You do not qualify for the scholarship.


### If/Elif/Else Statements

The **if/elif/else** structure allows you to check multiple conditions in sequence. Only one block of code will run, based on which condition is `True`.

#### Syntax:
```python
if condition1:
    # code to execute if condition1 is true
elif condition2:
    # code to execute if condition2 is true
else:
    # code to execute if none of the above conditions are true
```

In [ ]:
# Example: If/Elif/Else statement
gpa = 3.1
if gpa > 3.5:
    print("You qualify for the highest scholarship.")
elif gpa > 3.0:
    print("You qualify for the general scholarship.")
else:
    print("You do not qualify for a scholarship.")

You qualify for the general scholarship.


## Loops

### Loops in Python

Loops allow you to repeat a block of code multiple times. Python supports two types of loops:

- `for` loops
- `while` loops

---

### 1. For Loops

The `for` loop in Python is used to iterate over a sequence (such as a list, tuple, or string) or other iterable objects. It allows you to execute a block of code for each element in the sequence.

#### Syntax:
```python
for variable in sequence:
    # code to execute for each item in the sequence
```

In [ ]:
for x in range(1, 6):
    print(x, "squared is", x * x)

1 squared is 1
2 squared is 4
3 squared is 9
4 squared is 16
5 squared is 25


### 2. The `range()` Function

The `range()` function generates a sequence of numbers. It can be used to specify the range of values for a loop.

#### Syntax:
```python
range(start, stop, step)
```
- `start`: The first value in the range (inclusive).
- `stop`: The last value (exclusive).
- `step`: The difference between consecutive values (optional).


In [ ]:
for x in range(5, 0, -1):
    print(x)
print("Blastoff!")

5
4
3
2
1
Blastoff!


### 3. Cumulative Loops

A cumulative loop keeps track of a total, typically initialized outside of the loop and incremented inside the loop.


In [ ]:
sum = 0
for i in range(1, 11):
    sum = sum + (i * i)
print("Sum of the first 10 squares is", sum)

Sum of the first 10 squares is 385


### 4. While Loops

A `while` loop repeats a block of code as long as a condition is `True`. It is typically used when the number of iterations is not known in advance.

#### Syntax:
```python
while condition:
    # code to execute while the condition is true
```


In [ ]:
number = 1
while number < 200:
    print(number, end=" ")
    number = number * 2

1 2 4 8 16 32 64 128 

### 5. Loop Control Statements

Loop control statements allow you to modify the flow of a loop:

- `break`: Exits the loop prematurely.
- `continue`: Skips the current iteration and moves to the next one.
- `pass`: Does nothing, used as a placeholder.

In [ ]:
for i in range(1, 11):
    if i == 5:
        break
    print(i)

1
2
3
4


In [ ]:
for i in range(1, 11):
    if i == 5:
        continue
    print(i)

1
2
3
4
6
7
8
9
10


## Functions

### Introduction to Functions

A function is a block of reusable code that performs a specific task. Functions allow you to break your program into smaller, modular chunks and avoid repetition.

In Python, you define a function using the `def` keyword.

---

### 1. Defining a Function

To define a function, use the following syntax:

#### Syntax:
```python
def function_name(parameters):
    # code block to execute
```

In [ ]:
def greet():
    print("Hello, world!")

greet()  # Output: Hello, world!

Hello, world!


### 2. Function Parameters

Functions can accept parameters (also called arguments), which are values that you can pass into the function.

#### Syntax:
```python
def function_name(parameter1, parameter2):
    # code block that uses parameters
```

In [ ]:
def greet(name):
    print(f"Hello, {name}!")

greet("Alice")  # Output: Hello, Alice!

Hello, Alice!


### 3. Return Values

A function can return a value using the `return` statement.

In [ ]:
def square(x):
    return x * x

result = square(5)
print("Square of 5 is", result)  # Output: Square of 5 is 25

Square of 5 is 25


### 4. Default Parameters

You can assign default values to function parameters. If a value is not provided when calling the function, the default value will be used.


In [ ]:
def greet(name="Guest"):
    print(f"Hello, {name}!")

greet()        # Output: Hello, Guest!
greet("John")  # Output: Hello, John!

Hello, Guest!
Hello, John!


### 5. Keyword Arguments

Python allows you to call a function using **keyword arguments**, where the argument name is specified during the function call.

In [ ]:
def display_info(name, age):
    print(f"Name: {name}, Age: {age}")

display_info(age=30, name="Alice")  # Output: Name: Alice, Age: 30

Name: Alice, Age: 30


### 6. Variable-Length Arguments

You can define functions that accept an arbitrary number of arguments by using `*args` for positional arguments and `**kwargs` for keyword arguments.


#### Example of `*args`:

In [ ]:
del sum
def add_numbers(*args):
    result = sum(args)
    print("Sum:", result)

add_numbers(1, 2, 3, 4)  # Output: Sum: 10

Sum: 10


#### Example of `**kwargs`:

In [ ]:
def display_info(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

display_info(name="Alice", age=30, city="New York")

name: Alice
age: 30
city: New York


### 7. Functions as First-Class Objects

In Python, functions are treated as first-class objects, meaning they can be assigned to variables, passed as arguments, or returned from other functions.


In [ ]:
def shout(text):
    return text.upper()

def whisper(text):
    return text.lower()

# Assign functions to variables
action = shout
print(action("Hello"))  # Output: HELLO

# Pass functions as arguments
def greet(func):
    greeting = func("Hi there")
    print(greeting)

greet(whisper)  # Output: hi there

HELLO
hi there


### 8. Lambda Functions

A **lambda function** is a small anonymous function that can have any number of input parameters but only one expression.

#### Syntax:
```python
lambda arguments: expression
```


In [ ]:
square = lambda x: x * x
print(square(5))  # Output: 25

25


### 9. Higher-Order Functions

A **higher-order function** is a function that takes another function as an argument, or returns a function as a result.


In [ ]:
def apply_function(func, value):
    return func(value)

result = apply_function(lambda x: x * 2, 10)
print(result)  # Output: 20

20


# More Advanced Topics

## Data Structures

Python provides several built-in data structures that allow you to store and manage collections of data efficiently. The most commonly used data structures are:

- Lists
- Tuples
- Sets
- Dictionaries

---

### 1. Lists

A **list** is an ordered collection of items, which can be of different types. Lists are mutable, meaning you can modify their contents after creation.

#### Syntax:
```python
my_list = [item1, item2, item3]
```

In [ ]:
fruits = ["apple", "banana", "cherry"]
print(fruits)  # Output: ['apple', 'banana', 'cherry']

['apple', 'banana', 'cherry']


#### List Operations:
- **Append**: Adds an item to the end of the list.

In [ ]:
fruits.append("orange")
print(fruits)  # Output: ['apple', 'banana', 'cherry', 'orange']

['apple', 'banana', 'cherry', 'orange']



- **Insert**: Inserts an item at a specific index.

In [ ]:
fruits.insert(1, "blueberry")
print(fruits)  # Output: ['apple', 'blueberry', 'banana', 'cherry', 'orange']

['apple', 'blueberry', 'banana', 'cherry', 'orange']


- **Remove**: Removes the first occurrence of an item.

In [ ]:
fruits.remove("banana")
print(fruits)  # Output: ['apple', 'blueberry', 'cherry', 'orange']

['apple', 'blueberry', 'cherry', 'orange']



- **Indexing and Slicing**: Access items by index.

In [ ]:
print(fruits[0])  # Output: 'apple'
print(fruits[1:3])  # Output: ['blueberry', 'cherry']

apple
['blueberry', 'cherry']


#### Using Lists as Stacks:
Lists can be used as stacks where elements are added or removed from the end.

In [ ]:
stack = ["a", "b", "c"]
stack.append("d")  # Output: ['a', 'b', 'c', 'd']
stack.pop()        # Output: 'd'

'd'

---
### 2. Tuples

A **tuple** is similar to a list but immutable, meaning you cannot modify its contents once created.

#### Syntax:
```python
my_tuple = (item1, item2, item3)
```

In [ ]:
coordinates = (10, 20)
print(coordinates)  # Output: (10, 20)

(10, 20)


#### Creating a Tuple with One Item:
When creating a tuple with a single element, you need a trailing comma to differentiate it from a regular parenthesis.


In [ ]:
singleton = (2,)
print(singleton)  # Output: (2,)

(2,)


---
### 3. Sets

A **set** is an unordered collection of unique items. Sets are mutable, but they do not allow duplicates.

#### Syntax:
```python
my_set = {item1, item2, item3}
```


In [ ]:
colors = {"red", "green", "blue"}
print(colors)  # Output: {'red', 'green', 'blue'}

{'blue', 'red', 'green'}


#### Set Operations:
- **Add**: Adds an item to the set.
  ```python
  colors.add("yellow")
  print(colors)  # Output: {'red', 'yellow', 'green', 'blue'}
  ```

- **Set Operations**: Perform union, intersection, difference, and symmetric difference on sets.
  ```python
  setA = {"a", "b", "c"}
  setB = {"c", "d", "e"}
  
  print(setA | setB)  # Union: {'a', 'b', 'c', 'd', 'e'}
  print(setA & setB)  # Intersection: {'c'}
  print(setA - setB)  # Difference: {'a', 'b'}
  print(setA ^ setB)  # Symmetric Difference: {'a', 'b', 'd', 'e'}
  ```

---

### 4. Dictionaries

A **dictionary** is an unordered collection of key-value pairs. Each key must be unique, and keys are used to access the corresponding values.

#### Syntax:
```python
my_dict = {key1: value1, key2: value2}
```

In [ ]:
student = {"name": "Alice", "age": 24, "major": "Computer Science"}
print(student)  # Output: {'name': 'Alice', 'age': 24, 'major': 'Computer Science'}

{'name': 'Alice', 'age': 24, 'major': 'Computer Science'}


#### Dictionary Operations:
- **Add/Modify Entries**: Assign a value to a key.
  ```python
  student["grade"] = "A"
  print(student)  # Output: {'name': 'Alice', 'age': 24, 'major': 'Computer Science', 'grade': 'A'}
  ```

- **Remove Entries**: Delete a key-value pair using `del`.
  ```python
  del student["major"]
  print(student)  # Output: {'name': 'Alice', 'age': 24, 'grade': 'A'}
  ```

- **Iterate Over a Dictionary**:
  ```python
  for key, value in student.items():
      print(f"{key}: {value}")
  ```
  #### Output:
  ```
  name: Alice
  age: 24
  grade: A
  ```

#### Copying Dictionaries:
To copy a dictionary, use the `.copy()` method.

In [ ]:
original = {1: "hello"}
copy_dict = original.copy()
original[1] = "goodbye"
print(original)  # Output: {1: 'goodbye'}
print(copy_dict) # Output: {1: 'hello'}

{1: 'goodbye'}
{1: 'hello'}


### 5. Summary of Data Structures

| Data Structure | Mutable | Ordered | Allows Duplicates |
|----------------|---------|---------|-------------------|
| List           | Yes     | Yes     | Yes               |
| Tuple          | No      | Yes     | Yes               |
| Set            | Yes     | No      | No                |
| Dictionary     | Yes     | No      | Keys: No, Values: Yes |

---


## NumPy and Scientific Computing

### Introduction

**NumPy** (Numerical Python) is a powerful library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a wide collection of mathematical functions to operate on these arrays efficiently. It is widely used in data science, machine learning, and scientific computing due to its speed, flexibility, and ease of use.

### Key Features of NumPy

1. **Efficient Memory Usage**: NumPy arrays use contiguous blocks of memory, allowing for efficient memory access and fast computation compared to Python lists.
2. **Vectorized Operations**: NumPy allows operations on entire arrays without needing loops. These vectorized operations are executed in compiled C code, making them significantly faster than traditional Python loops.
3. **Mathematical Functions**: NumPy provides optimized implementations of a wide range of mathematical functions, including linear algebra operations, random number generation, and Fourier transforms.
4. **Interoperability**: NumPy integrates seamlessly with other libraries such as Pandas, SciPy, Pytorch, and TensorFlow. It also supports data sharing with external libraries in C/C++ and Fortran.

---

### Use Cases of NumPy

1. **Scientific Computing**: NumPy is the backbone for many scientific computing tasks, such as solving linear algebra problems, numerical integration, and optimization.
2. **Data Analysis**: NumPy is often used to handle large datasets along with pandas.
3. **Machine Learning**: NumPy provides efficient numerical operations on large datasets and is often used for data preprocessing in machine learning pipelines.
4. **Image Processing**: NumPy arrays are used to store pixel data and perform image transformations.
---

### Why Use NumPy?

1. **Speed and Performance**: NumPy is written in C, allowing for performance optimizations that make it much faster than standard Python, especially for large datasets and numerical calculations.
2. **Vectorized Operations**: NumPy enables you to apply operations directly to entire arrays, matrices, or vectors without the need for explicit loops. This makes the code cleaner, more readable, and faster. The C code in the backend of Numpy uses very efficicent multi-threaded libraries such as BLAS and LAPACK.
   
   Example:
   ```python
   import numpy as np
   # Vectorized addition
   arr1 = np.array([1, 2, 3])
   arr2 = np.array([4, 5, 6])
   result = arr1 + arr2  # Output: array([5, 7, 9])
   ```

3. **Broadcasting**: NumPy automatically handles arithmetic operations between arrays of different shapes, allowing them to be broadcasted across one another. This makes it easy to apply operations across dimensions without reshaping data manually.

   Example:
   ```python
   import numpy as np
   a = np.array([1, 2, 3])
   b = np.array([[10], [20], [30]])
   result = a + b
   # Output:
   # array([[11, 12, 13],
   #        [21, 22, 23],
   #        [31, 32, 33]])
   ```

4. **Multi-dimensional Arrays**: NumPy supports multi-dimensional arrays (also known as tensors) that can represent scalars, vectors, matrices, and higher-dimensional data structures.

   Example:
   ```python
   matrix = np.array([[1, 2, 3], [4, 5, 6]])
   ```

5. **Indexing and Slicing**: NumPy allows advanced indexing and slicing, making it easier to work with subsets of data.

   Example:
   ```python
   arr = np.array([1, 2, 3, 4, 5])
   print(arr[1:4])  # Output: array([2, 3, 4])
   ```

   Example:
   ```python
   arr = np.array([1, 2, 3, 4, 5])
   print(arr[[1,3,4]])  # Output: array([2, 4, 5])
   ```

6. **Linear Algebra**: NumPy has built-in functions for matrix multiplication, inversion, and decompositions, which are essential for many scientific and engineering problems.

   Example:
   ```python
   import numpy as np
   A = np.array([[1, 2], [3, 4]])
   B = np.linalg.inv(A)  # Inverse of matrix A
   ```

7. **Random Number Generation**: NumPy’s random module provides functions to generate random numbers from various distributions, making it useful for simulations and probabilistic modeling.

   Example:
   ```python
   random_numbers = np.random.rand(3, 3)  # 3x3 array of random numbers between 0 and 1
   ```

8. **Handling Missing Data**: NumPy arrays support NaN (Not a Number) values, which can be useful when working with incomplete datasets or math operations which sometimes involve nan values (such as division by zero).

   Example:
   ```python
   arr = np.array([1, 2, np.nan, 4])
   print(np.isnan(arr))  # Output: array([False, False,  True, False])
   ```

---

### Benefits of Using NumPy

- **Speed**: Operations on large datasets are much faster using NumPy compared to Python lists due to its low-level implementation in C.
- **Memory Efficiency**: NumPy arrays consume less memory than traditional Python lists.
- **Ease of Use**: The ability to perform vectorized operations simplifies code and reduces the need for explicit loops.
- **Rich Ecosystem**: NumPy is part of the larger scientific Python ecosystem and integrates well with libraries like Pandas, SciPy, and Matplotlib.

---

This section introduces the power and flexibility of NumPy for scientific computing, highlighting why it’s essential for handling large datasets, performing fast vectorized operations, and working in fields like machine learning, data analysis, and scientific research.


## Basic Examples of NumPy Usage

### 1. Creating Arrays

NumPy arrays are the core data structure in NumPy. You can create arrays in several ways:


#### Example: Creating 1D and 2D arrays

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)

# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array (matrix):\n", arr2)

1D array: [1 2 3 4 5]
2D array (matrix):
 [[1 2 3]
 [4 5 6]]


#### Example: Creating arrays filled with zeros, ones, or random values


In [ ]:
zeros_array = np.zeros((3, 3))
print("Array of zeros:\n", zeros_array)

# Array of ones
ones_array = np.ones((2, 4))
print("Array of ones:\n", ones_array)

# Array of random values between 0 and 1
random_array = np.random.rand(3, 3)
print("Array of random values:\n", random_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of random values:
 [[0.7437684  0.72894789 0.98767147]
 [0.79180152 0.27377165 0.30139987]
 [0.12106889 0.30486179 0.42473532]]


#### Example: Creating arrays with ranges and evenly spaced values

In [ ]:
# Array with values from 0 to 9
range_array = np.arange(10)
print("Array with values from 0 to 9:", range_array)

# Array of evenly spaced values between 1 and 10
linspace_array = np.linspace(1, 10, 5)
print("Array of 5 evenly spaced values between 1 and 10:", linspace_array)

Array with values from 0 to 9: [0 1 2 3 4 5 6 7 8 9]
Array of 5 evenly spaced values between 1 and 10: [ 1.    3.25  5.5   7.75 10.  ]


---

### 2. Array Indexing and Slicing

You can access and modify elements in a NumPy array just like you would with Python lists.

#### Example: Indexing and slicing 1D arrays

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Accessing individual elements
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing
print("Slice from index 1 to 3:", arr[1:4])

First element: 10
Last element: 50
Slice from index 1 to 3: [20 30 40]


#### Example: Indexing and slicing 2D arrays

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing individual elements
print("Element at row 1, column 2:", matrix[1, 2])  # Output: 6

# Slicing rows and columns
print("First two rows:\n", matrix[:2, :])

Element at row 1, column 2: 6
First two rows:
 [[1 2 3]
 [4 5 6]]


---

### 3. Basic Mathematical Operations

NumPy allows element-wise operations between arrays and scalars.

#### Example: Element-wise addition, multiplication, and exponentiation


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
print("Element-wise addition:", arr1 + arr2)

# Element-wise multiplication
print("Element-wise multiplication:", arr1 * arr2)

# Element-wise exponentiation
print("Element-wise exponentiation:", arr1 ** 2)

Element-wise addition: [5 7 9]
Element-wise multiplication: [ 4 10 18]
Element-wise exponentiation: [1 4 9]


#### Example: Array and scalar operations

In [ ]:
# Adding a scalar to an array
print("Array + scalar:", arr1 + 10)

# Multiplying an array by a scalar
print("Array * scalar:", arr1 * 3)

Array + scalar: [11 12 13]
Array * scalar: [3 6 9]


---

### 4. Statistical and Mathematical Functions

NumPy provides many useful mathematical functions.

#### Example: Calculating mean, sum, and standard deviation


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard deviation:", np.std(arr))

Sum: 15
Mean: 3.0
Standard deviation: 1.4142135623730951


#### Example: Finding the minimum and maximum values

In [ ]:
print("Min:", np.min(arr))
print("Max:", np.max(arr))

Min: 1
Max: 5


#### Example: Transposing a matrix

In [ ]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print("Original matrix:\n", matrix)
print("Transposed matrix:\n", np.transpose(matrix))

Original matrix:
 [[1 2]
 [3 4]
 [5 6]]
Transposed matrix:
 [[1 3 5]
 [2 4 6]]


---

### 5. Broadcasting

NumPy automatically handles arithmetic operations between arrays of different shapes by **broadcasting**.

#### Example: Broadcasting a 1D array to a 2D array

In [ ]:
arr = np.array([1, 2, 3])
matrix = np.array([[10], [20], [30]])

# Broadcasting the 1D array across the rows of the 2D array
result = arr + matrix
print("Broadcasting result:\n", result)

Broadcasting result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


---

### 6.Vectorized Operations vs. Loops

One of the main advantages of NumPy is its ability to perform vectorized operations, which are much faster than equivalent operations using Python loops.

#### Example: Summing Elements

In [ ]:
import time

# Large array
arr = np.arange(1e7)

# Summing using a loop
start_time = time.time()
total = 0
for x in arr:
    total += x
print("Sum using loop:", total)
print("Time taken by loop:", time.time() - start_time, "seconds")

Sum using loop: 49999995000000.0
Time taken by loop: 2.317579746246338 seconds


In [ ]:
start_time = time.time()
total = np.sum(arr)
print("Sum using NumPy:", total)
print("Time taken by NumPy:", time.time() - start_time, "seconds")

Sum using NumPy: 49999995000000.0
Time taken by NumPy: 0.0156707763671875 seconds


### 7. Exercises

### Exercise 1: Matrix Multiplication
#### Task:
- Write a function that performs matrix multiplication of two 2D arrays, `A` and `B`, using nested loops.
- Then, rewrite the function using NumPy's vectorized `np.dot()` or `@` operator.
- Compare the performance of the loop implementation with the vectorized version.

#### Hints:
- Use the following dimensions for the matrices: `A` of shape (500, 500) and `B` of shape (500, 500).
- Measure the execution time using `%timeit`.

---

In [ ]:
def matrix_multiply_loops(A, B):
    result = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Test with two random 500x500 matrices
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)
%timeit matrix_multiply_loops(A, B)

725 ms ± 82 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
def matrix_multiply_vectorized(A, B):
    return np.matmul(A, B)

# Vectorized matrix multiplication
%timeit matrix_multiply_vectorized(A, B)

27.7 µs ± 2.66 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
np.abs(matrix_multiply_loops(A, B) - matrix_multiply_vectorized(A, B)).sum()

1.5010215292932116e-11

### Exercise 2: Euclidean Distance Calculation

#### Task:
- Given two arrays `A` and `B`, each containing N points in a D-dimensional space, compute the Euclidean distance between every point in `A` and every point in `B` using nested loops.
- Rewrite the function using NumPy’s broadcasting and vectorized operations to compute all distances at once.
- Compare the performance of both implementations.

#### Hints:
- Start by writing a nested loop implementation using the formula:
  $\text{distance} = \sqrt{(x_1 - x_2)^2 + (y_1 - y_2)^2 + \ldots}$
- Use `np.linalg.norm()` or broadcasting for the vectorized version.

---

In [ ]:
def euclidean_distance_loops(A, B):
    result = np.zeros((A.shape[0], B.shape[0]))
    for i in range(A.shape[0]):
        for j in range(B.shape[0]):
            result[i, j] = np.sqrt(np.sum((A[i] - B[j]) ** 2))
    return result

# Random points in 3D space
A = np.random.rand(1000, 3)
B = np.random.rand(1000, 3)
%timeit euclidean_distance_loops(A, B)

9.07 s ± 1.85 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
def euclidean_distance_vectorized(A, B):
    diff = A[:, np.newaxis, :] - B
    return np.sqrt(np.sum(diff ** 2, axis=-1))

# Vectorized Euclidean distance calculation
%timeit euclidean_distance_vectorized(A, B)

79.7 ms ± 11.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
A = np.random.rand(50, 3)
B = np.random.rand(50, 3)

np.abs(euclidean_distance_loops(A, B) - euclidean_distance_vectorized(A, B)).sum()

0.0

### Exercise 3: Convolution of an Image with a Kernel

#### Task:
- Write a function that applies a convolution operation on a 2D array (representing an image) using a 3x3 kernel, implemented using loops.
- Then, rewrite the function using Scipy's `scipy.signal.convolve2d()` for a vectorized approach.
- Test the performance of both implementations with a large 2D array (e.g., 1000x1000 image).

#### Hints:
- For the loop implementation, use nested loops to iterate over the image array and apply the kernel.
- Compare performance using `%timeit`.

---

In [ ]:
def convolution_loops(image, kernel):
    # In traditional image processing, convolution operations can flip the kernel before applying it,
    kernel = np.flipud(np.fliplr(kernel))
    # Get the dimensions of the image and the kernel
    kernel_height, kernel_width = kernel.shape
    image_height, image_width = image.shape

    # Calculate the dimensions of the output array
    output_height = image_height - kernel_height + 1
    output_width = image_width - kernel_width + 1

    # Initialize the output array with zeros
    output = np.zeros((output_height, output_width))

    # Perform convolution using nested loops
    for i in range(output_height):
        for j in range(output_width):
            # Extract the current region of interest from the image
            region = image[i:i + kernel_height, j:j + kernel_width]
            # Element-wise multiplication and summation
            output[i, j] = np.sum(region * kernel)

    return output


# Random 64x64 image and 3x3 kernel
image = np.random.rand(128, 128)
kernel = np.array([[1, 0, -1], [1, 0, -1], [1, 0, -1]])
%timeit convolution_loops(image, kernel)

115 ms ± 27.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
from scipy.signal import convolve2d

def convolution_vectorized(image, kernel):
    return convolve2d(image, kernel, mode='valid')

# Vectorized convolution using scipy
%timeit convolution_vectorized(image, kernel)

946 µs ± 203 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
np.abs(convolution_loops(image, kernel) - convolution_vectorized(image, kernel)).sum()

6.150635556423367e-13

### Exercise 4: Polynomial Evaluation

#### Task:
- Write a function that evaluates a polynomial for a given set of x-values using a loop. For a polynomial of the form:
  $P(x) = a_0 + a_1x + a_2x^2 + \dots + a_nx^n$
  - Use the coefficients `a = [a_0, a_1, a_2, \dots, a_n]` and compute the polynomial for each element in an array `x`.
- Then, rewrite the function using NumPy’s vectorized operations (e.g., `np.polyval()`).
- Compare the performance of both implementations with a large number of x-values.

#### Hints:
- For the loop implementation, use a for-loop to iterate over the polynomial terms.
- For the vectorized approach, consider using `np.polyval()` or `np.power()`.

---

In [ ]:
def polynomial_evaluation_loops(coefficients, x_values):
    result = np.zeros_like(x_values)
    for i, coeff in enumerate(coefficients):
        result += coeff * (x_values ** i)
    return result

# Polynomial coefficients and x values
coefficients = [1, -2, 3, 4]  # Represents 1 - 2x + 3x^2 + 4x^3
x_values = np.linspace(-10, 10, 100000)
%timeit polynomial_evaluation_loops(coefficients, x_values)

3.71 ms ± 85.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
def polynomial_evaluation_vectorized(coefficients, x_values):
    return np.polyval(coefficients[::-1], x_values)

# Vectorized polynomial evaluation
%timeit polynomial_evaluation_vectorized(coefficients, x_values)

1.36 ms ± 297 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
np.abs(polynomial_evaluation_loops(coefficients, x_values) - polynomial_evaluation_vectorized(coefficients, x_values)).sum()

5.451614715212827e-09

### Exercise 5: Monte Carlo Simulation for Pi Estimation

#### Task:
- Implement a Monte Carlo simulation to estimate the value of π by generating random points inside a unit square and counting how many fall inside the unit circle, using loops.
- Then, rewrite the simulation using NumPy’s vectorized random number generation and array operations.
- Compare the performance of both implementations when simulating 1 million random points.

#### Hints:
- The formula to estimate π is:
  $\pi \approx 4 \times \frac{\text{points inside circle}}{\text{total points}}$
- Use `np.random.rand()` for the vectorized version.

---

In [ ]:
def monte_carlo_pi_loops(n_points):
    inside_circle = 0
    for _ in range(n_points):
        x, y = np.random.rand(), np.random.rand()
        if np.sqrt(x ** 2 + y ** 2) <= 1:
            inside_circle += 1
    return (inside_circle / n_points) * 4

# Estimate Pi using 1 million points
%timeit monte_carlo_pi_loops(1000000)

2.49 s ± 548 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
def monte_carlo_pi_vectorized(n_points):
    points = np.random.rand(n_points, 2)
    distances = np.sqrt(points[:, 0] ** 2 + points[:, 1] ** 2)
    inside_circle = np.sum(distances <= 1)
    return (inside_circle / n_points) * 4

# Vectorized Pi estimation
%timeit monte_carlo_pi_vectorized(1000000)

30.5 ms ± 6.85 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
